"""Rebuild local export assets and a single-file studio. No network or packages needed."""
from pathlib import Path
import base64
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
fonts = ''.join('@font-face{font-family:"Neue Montreal";font-style:normal;font-weight:' + weight + ';font-display:swap;src:url(data:font/woff2;base64,' + base64.b64encode((ROOT / 'vendor' / 'brand' / name).read_bytes()).decode() + ') format("woff2")}\n' for name, weight in [('regular.woff2','400'),('medium.woff2','500')])
(ROOT / 'src' / 'brand.css').write_text('/* Generated by build.py from brand-theme.css and bundled fonts. */\n' + fonts + (ROOT / 'src' / 'brand-theme.css').read_text())
def css_rules(css):
    rules, depth, start = [], 0, 0
    for i, char in enumerate(css):
        if char == '{':
            depth += 1
        elif char == '}':
            depth -= 1
            if depth == 0:
                rules.append(css[start:i + 1].strip())
                start = i + 1
    return rules

def runtime_brand_css():
    """Keep only the brand-theme rules whose classes the exported editor actually uses, without embedded fonts."""
    used = {'editor', 'runtime-brand', 'jarrang-wordmark', 'standalone', 'status'}
    for name in ['controls.js', 'rich-editor.js', 'runtime.js', 'runtime.css', 'controls.css']:
        used |= set(re.findall(r'[a-z][a-z0-9_-]*', (ROOT / 'src' / name).read_text()))
    wanted = lambda selector: all(token in used for token in re.findall(r'[.#]([a-z][a-z0-9_-]*)', selector))
    def filtered(rule):
        head, body = rule.split('{', 1)
        if head.startswith('@media'):
            inner = [r for r in map(filtered, css_rules(body.rsplit('}', 1)[0])) if r]
            return head + '{\n' + '\n'.join(inner) + '\n}' if inner else ''
        selectors = [s.strip() for s in head.split(',') if wanted(s)]
        return ', '.join(selectors) + '{' + body if selectors else ''
    theme = re.sub(r'/\*.*?\*/', '', (ROOT / 'src' / 'brand-theme.css').read_text(), flags=re.S)
    css = '\n'.join(r for r in map(filtered, css_rules(theme)) if r)
    return '/* Generated by build.py from brand-theme.css: only what exported SFMC editors use, with system fonts. */\n' + css.replace("'Neue Montreal', ", '') + '\n'
(ROOT / 'src' / 'runtime-brand.css').write_text(runtime_brand_css())
def minify_css(css):
    """Whitespace and comment stripping only. The bundled sheets contain no url() values, so this cannot alter data."""
    assert 'url(' not in css
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    css = re.sub(r'\s+', ' ', css)
    return re.sub(r' ?([{};,]) ?', r'\1', css).replace(';}', '}').strip() + '\n'
def read(path):
    return (ROOT / path).read_text()
# One request per type: the SDK, shared engine, editor controls and runtime load in the order the separate scripts did.
# The rich-text editor is only in the second variant, which exported pages use when a module has a richtext field.
def js_bundle(rich):
    parts = ['vendor/blocksdk.js', 'src/logic.js', 'src/runtime-core.js'] + (['src/rich-editor.js'] if rich else []) + ['src/controls.js', 'src/runtime.js']
    return '/* Generated by build.py: Salesforce Block SDK (BSD-3-Clause, see BLOCKSDK-LICENSE.txt), logic, runtime-core, ' + ('rich-editor, ' if rich else '') + 'controls and runtime. */\n' + '\n;\n'.join(read(p) for p in parts)
assets = {
    'runtime.bundle.js': js_bundle(False),
    'runtime.rich.bundle.js': js_bundle(True),
    'runtime.bundle.css': '/* Generated by build.py: runtime, controls and runtime-brand styles. */\n' + minify_css(''.join(read('src/' + name) for name in ['runtime.css', 'controls.css', 'runtime-brand.css'])),
    'brand.css': read('src/brand.css'),
    'BLOCKSDK-LICENSE.txt': read('vendor/BLOCKSDK-LICENSE.txt'),
}
(ROOT / 'src' / 'export-assets.js').write_text('/* Generated by build.py. Local export dependencies. */\nwindow.EXPORT_ASSET_VERSION = '+json.dumps(hashlib.sha256(json.dumps(assets, sort_keys=True).encode()).hexdigest()[:16])+';\nwindow.EXPORT_ASSETS = ' + json.dumps(assets, ensure_ascii=True) + ';\n')
html = (ROOT / 'index.html').read_text()
for css in ['studio.css', 'controls.css', 'brand.css', 'code-editor.css']:
    html = html.replace('<link rel="stylesheet" href="src/' + css + '">', '<style>' + (ROOT / 'src' / css).read_text() + '</style>')
def inline_script(match):
    code = (ROOT / match[1]).read_text()
    code = re.sub(r'</script', r'<\\/script', code, flags=re.I)
    return '<script>' + code + '</script>'
html = re.sub(r'<script src="([^"]+)"></script>', inline_script, html)
(ROOT / 'Open-Block-Studio.html').write_text(html)
print('Built src/export-assets.js and Open-Block-Studio.html')

site = REPO_ROOT / 'docs' / 'studio'
site.mkdir(parents=True, exist_ok=True)
(site / 'index.html').write_text(html)
(REPO_ROOT / 'docs' / '.nojekyll').write_text('')
