"""Rebuild local export assets and a single-file studio. No network or packages needed."""
from pathlib import Path
import base64
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parent
fonts = ''.join('@font-face{font-family:"Neue Montreal";font-style:normal;font-weight:' + weight + ';font-display:swap;src:url(data:font/woff2;base64,' + base64.b64encode((ROOT / 'vendor' / 'brand' / name).read_bytes()).decode() + ') format("woff2")}\n' for name, weight in [('regular.woff2','400'),('medium.woff2','500')])
(ROOT / 'src' / 'brand.css').write_text('/* Generated by build.py from brand-theme.css and bundled fonts. */\n' + fonts + (ROOT / 'src' / 'brand-theme.css').read_text())
assets = {name: (ROOT / 'src' / name).read_text() for name in ['core.js', 'logic.js', 'rich-editor.js', 'controls.js', 'controls.css', 'runtime.js', 'runtime.css', 'brand.css']}
assets.update({name: (ROOT / 'vendor' / name).read_text() for name in ['blocksdk.js', 'BLOCKSDK-LICENSE.txt']})
(ROOT / 'src' / 'export-assets.js').write_text('/* Generated by build.py. Local export dependencies. */\nwindow.EXPORT_ASSET_VERSION = '+json.dumps(hashlib.sha256(json.dumps(assets, sort_keys=True).encode()).hexdigest()[:16])+';\nwindow.EXPORT_ASSETS = ' + json.dumps(assets, ensure_ascii=True) + ';\n')
html = (ROOT / 'index.html').read_text()
for css in ['studio.css', 'controls.css', 'brand.css', 'code-editor.css']:
    html = html.replace('<link rel="stylesheet" href="src/' + css + '">', '<style>' + (ROOT / 'src' / css).read_text() + '</style>')
def inline_script(match):
    code = (ROOT / match[1]).read_text()
    code = re.sub(r'</script', r'<\\/script', code, flags=re.I)
    return '<script>' + code + '</script>'
html = re.sub(r'<script src="([^"]+)"></script>', inline_script, html)
(ROOT / 'Open-Block-Studio.html').write_text(html)
print('Built src/export-assets.js and Open-Block-Studio.html')

site = ROOT / 'docs' / 'studio'
site.mkdir(parents=True, exist_ok=True)
(site / 'index.html').write_text(html)
(ROOT / 'docs' / '.nojekyll').write_text('')
